Enable ntruprime sntrup761
open-quantum-safe/liboqs-rust pull request #180
Opened 2023-01-31 06:45 UTC by loganaden

2023-02-01 21:11 UTC, dstebila submitted a review, later dismissed

2023-02-06 09:52 UTC, thomwiggers requested changes
You missed a feature which is required for this to build correctly. Once that's added, this should be ready to be merged.

2023-02-06 09:52 UTC, thomwiggers commented on oqs/Cargo.toml
>  frodokem = ["oqs-sys/frodokem"]
```suggestion
frodokem = ["oqs-sys/frodokem"]
ntruprime = ["oqs-sys/ntruprime"]
```

2023-02-06 10:55 UTC, loganaden commented on oqs/Cargo.toml
>  frodokem = ["oqs-sys/frodokem"]
Thanks. PR updated.

2023-02-06 10:56 UTC, thomwiggers approved these changes

2023-02-06 11:48 UTC, loganaden commented
It appears that the branch needs to be merged with the latest commit from @thomwiggers before it's merged automatically ?I've done this. Waiting for the next CI run to be allowed.

2023-02-06 12:48 UTC, thomwiggers commented
I wish "approve and run" would stick, but alas. Okay, this should finally go through when CI passes now.

2023-02-06 13:04 UTC, merged

2023-02-06 13:04 UTC, thomwiggers commented
Thanks :)

2023-08-26 16:14 UTC, Sculas commented
I was taking a look at the codebase, and I noticed that NTRU Prime was missing from here:
https://github.com/open-quantum-safe/liboqs-rust/blob/6918c275becb51780ec4761c6974a2843726f3f9/oqs-sys/build.rs#L61-L78
This made me think that the NTRU Prime algorithm would always be disabled, but tests are saying otherwise.
How can it be that NTRU Prime is being linked without it being toggled on? Does it default to being linked?